title: "VerifyBot"
description: "Official documentation for VerifyBot by Afterparty Bot Labs"
show_downloads: false
theme_color: "#9933FF"
footer_brand: "Afterparty Bot Labs"
footer_link: "https://afterpartylabs.xyz"
logo: "/assets/images/verify-bot.png"
icon: "/assets/images/verify-bot.png"
favicon: "/assets/images/verify-bot.png"
cta_docs_url: "/"
cta_invite_url: "https://discord.com/api/oauth2/authorize?client_id=1325944440778657873&permissions=8&scope=applications.commands+bot"
cta_support_url: "https://discord.gg/BusuZp2G8w"
cta_website_url: "https://afterpartylabs.xyz"
url: "https://afteryparty.github.io"
baseurl: "/Verify-Bot-docs"
markdown: kramdown
